import type { PhenomenonProfile } from "./types";

export const PHENOMENA: PhenomenonProfile[] = [
  {
    id: "aurora-borealis",
    slug: "aurora-borealis",
    title: { en: "Aurora Borealis", ko: "오로라 (북극광)", ja: "オーロラ（北極光）" },
    aliases: ["aurora", "northern lights", "aurora borealis", "polar lights", "오로라", "북극광", "オーロラ", "北極光"],
    category: "space",
    scale: "planetary",
    shortExplanation: {
      en: "Charged particles from the Sun collide with gases in the upper atmosphere, releasing light that ripples across the polar sky.",
      ko: "태양에서 온 하전 입자가 고층 대기의 기체와 충돌하며 빛을 방출해 극지방 하늘에 커튼처럼 나타나는 현상입니다.",
      ja: "太陽から来た荷電粒子が高層大気の気体と衝突して光を放ち、極地の空にカーテンのように現れる現象です。",
    },
    cause: {
      en: "The solar wind carries charged particles toward Earth, where the planet's magnetic field funnels them toward the poles.",
      ko: "태양풍이 하전 입자를 지구로 실어 오고, 지구 자기장이 이 입자들을 극지방으로 모읍니다.",
      ja: "太陽風が荷電粒子を地球へ運び、地球の磁場がその粒子を極地へ導きます。",
    },
    mechanism: {
      en: "Particles accelerate along magnetic field lines and strike oxygen and nitrogen atoms, exciting their electrons; as electrons fall back, they emit photons.",
      ko: "입자가 자기력선을 따라 가속되어 산소·질소 원자와 충돌하며 전자를 들뜨게 하고, 전자가 원래 상태로 돌아올 때 광자를 방출합니다.",
      ja: "粒子は磁力線に沿って加速し、酸素や窒素の原子に衝突して電子を励起させ、電子が元に戻るときに光子を放出します。",
    },
    result: {
      en: "Green, red, and violet curtains of light shift across the night sky at altitudes of roughly 100 to 300 km.",
      ko: "고도 약 100~300km에서 초록·빨강·보라빛 커튼이 밤하늘을 가로지르며 일렁입니다.",
      ja: "高度およそ100〜300kmで、緑・赤・紫の光のカーテンが夜空を揺らめきながら横切ります。",
    },
    visualElements: [
      { en: "Sun emitting a stream of solar wind particles", ko: "태양에서 뿜어져 나오는 태양풍 입자 흐름", ja: "太陽から噴き出す太陽風の粒子の流れ" },
      { en: "Earth's magnetic field lines curving toward the poles", ko: "극지방으로 휘어지는 지구 자기력선", ja: "極地へ湾曲する地球の磁力線" },
      { en: "Layered curtains of green and magenta light", ko: "초록과 마젠타빛이 겹겹이 쌓인 빛 커튼", ja: "緑とマゼンタの光が層をなす光のカーテン" },
      { en: "Atmospheric layers with excited oxygen and nitrogen atoms", ko: "들뜬 산소·질소 원자가 있는 대기층", ja: "励起した酸素・窒素原子を含む大気層" },
    ],
    labelSuggestions: [
      { en: "Solar wind", ko: "태양풍", ja: "太陽風" },
      { en: "Magnetic field lines", ko: "자기력선", ja: "磁力線" },
      { en: "Excited oxygen (green 557 nm)", ko: "들뜬 산소 (초록 557nm)", ja: "励起酸素（緑 557nm）" },
      { en: "Thermosphere 100–300 km", ko: "열권 100~300km", ja: "熱圏 100〜300km" },
    ],
    annotations: [
      { en: "Charged particles enter along polar field lines", ko: "하전 입자가 극지 자기력선을 따라 진입", ja: "荷電粒子が極域の磁力線に沿って侵入する" },
      { en: "Collisions excite atmospheric gases", ko: "충돌이 대기 기체를 들뜨게 함", ja: "衝突が大気の気体を励起させる" },
      { en: "Photon emission produces visible color", ko: "광자 방출이 가시광 색을 만듦", ja: "光子の放出が可視光の色を生む" },
    ],
    styleNotes: {
      en: "Deep night-sky palette with luminous green and violet glow; emphasize flowing, curtain-like motion.",
      ko: "짙은 밤하늘 톤에 발광하는 초록·보라 빛; 커튼처럼 흐르는 움직임을 강조합니다.",
      ja: "深い夜空のトーンに発光する緑と紫の光。カーテンのように流れる動きを強調します。",
    },
    cautions: {
      en: "Aurora color depends on gas type and altitude; avoid depicting it as uniform or ground-level.",
      ko: "오로라 색은 기체 종류와 고도에 따라 달라집니다. 균일하거나 지면 높이로 묘사하지 마세요.",
      ja: "オーロラの色は気体の種類と高度で変わります。均一に、または地表の高さに描かないでください。",
    },
    negativeTerms: ["daytime sky", "rainbow arc", "ground-level flames", "uniform single color"],
    exampleInput: { en: "Explain how aurora borealis forms", ko: "오로라가 어떻게 생기는지 설명해줘", ja: "オーロラがどのように発生するか説明して" },
  },
  {
    id: "nuclear-fission",
    slug: "nuclear-fission",
    title: { en: "Nuclear Fission", ko: "핵분열", ja: "核分裂" },
    aliases: ["nuclear fission", "fission", "atomic fission", "uranium fission", "핵분열", "원자 분열", "核分裂"],
    category: "physics",
    scale: "atomic",
    shortExplanation: {
      en: "A heavy nucleus splits into lighter nuclei when struck by a neutron, releasing energy and additional neutrons that can sustain a chain reaction.",
      ko: "무거운 원자핵이 중성자에 맞아 가벼운 핵들로 쪼개지며 에너지와 추가 중성자를 방출하고, 이 중성자가 연쇄 반응을 일으킵니다.",
      ja: "重い原子核が中性子に当たって軽い核に分裂し、エネルギーと追加の中性子を放出して連鎖反応を維持します。",
    },
    cause: {
      en: "A free neutron is absorbed by a fissile nucleus such as uranium-235, making it unstable.",
      ko: "자유 중성자가 우라늄-235 같은 핵분열성 원자핵에 흡수되어 불안정해집니다.",
      ja: "自由中性子がウラン235のような核分裂性の原子核に吸収され、不安定になります。",
    },
    mechanism: {
      en: "The excited nucleus deforms and splits into two fragments, releasing binding energy along with two or three fast neutrons.",
      ko: "들뜬 원자핵이 변형되어 두 조각으로 쪼개지며 결합 에너지와 함께 두세 개의 빠른 중성자를 방출합니다.",
      ja: "励起した原子核が変形して2つの破片に分裂し、結合エネルギーとともに2〜3個の高速中性子を放出します。",
    },
    result: {
      en: "Released neutrons trigger further fissions, producing a self-sustaining chain reaction and large amounts of heat.",
      ko: "방출된 중성자가 추가 분열을 일으켜 스스로 유지되는 연쇄 반응과 막대한 열을 만듭니다.",
      ja: "放出された中性子がさらなる分裂を引き起こし、自己維持する連鎖反応と大量の熱を生み出します。",
    },
    visualElements: [
      { en: "Incoming neutron approaching a uranium nucleus", ko: "우라늄 핵으로 접근하는 중성자", ja: "ウラン核に近づく入射中性子" },
      { en: "Nucleus deforming and splitting into fragments", ko: "변형되어 조각으로 쪼개지는 원자핵", ja: "変形して破片に分裂する原子核" },
      { en: "Emitted neutrons branching to nearby nuclei", ko: "주변 핵으로 뻗어나가는 방출 중성자", ja: "近くの核へ枝分かれする放出中性子" },
      { en: "Energy release shown as radiant burst", ko: "빛나는 폭발로 표현된 에너지 방출", ja: "輝く放射として表現されたエネルギー放出" },
    ],
    labelSuggestions: [
      { en: "Incident neutron", ko: "입사 중성자", ja: "入射中性子" },
      { en: "Uranium-235 nucleus", ko: "우라늄-235 핵", ja: "ウラン235の核" },
      { en: "Fission fragments", ko: "분열 조각", ja: "核分裂片" },
      { en: "Chain reaction", ko: "연쇄 반응", ja: "連鎖反応" },
    ],
    annotations: [
      { en: "Neutron absorbed, nucleus becomes unstable", ko: "중성자 흡수로 핵이 불안정해짐", ja: "中性子を吸収し、核が不安定になる" },
      { en: "Nucleus splits, releasing energy", ko: "핵이 쪼개지며 에너지 방출", ja: "核が分裂してエネルギーを放出する" },
      { en: "New neutrons continue the reaction", ko: "새 중성자가 반응을 이어감", ja: "新たな中性子が反応を続ける" },
    ],
    styleNotes: {
      en: "Precise atomic-scale diagram with glowing energy accents; keep particles clearly distinguishable.",
      ko: "정밀한 원자 규모 다이어그램에 빛나는 에너지 강조; 입자를 명확히 구분되게 표현합니다.",
      ja: "光るエネルギーを強調した精密な原子スケールの図。粒子を明確に区別できるように描きます。",
    },
    cautions: {
      en: "Distinguish fission from fusion; do not depict a mushroom cloud for a controlled reactor context.",
      ko: "핵분열과 핵융합을 구분하세요. 제어된 원자로 맥락에서 버섯구름을 그리지 마세요.",
      ja: "核分裂と核融合を区別してください。制御された原子炉の文脈でキノコ雲を描かないでください。",
    },
    negativeTerms: ["mushroom cloud", "fusion of nuclei", "chemical explosion", "fire flames"],
    exampleInput: { en: "Visualize nuclear fission at the atomic scale", ko: "핵분열을 원자 규모로 시각화해줘", ja: "核分裂を原子スケールで視覚化して" },
  },
  {
    id: "lightning-formation",
    slug: "lightning-formation",
    title: { en: "Lightning Formation", ko: "번개 형성", ja: "雷の発生" },
    aliases: ["lightning", "lightning formation", "thunderbolt", "electric discharge storm", "번개", "낙뢰", "雷", "稲妻"],
    category: "earth",
    scale: "landscape",
    shortExplanation: {
      en: "Charge separation inside a storm cloud builds enormous electric potential that discharges as a bright lightning bolt.",
      ko: "폭풍 구름 내부의 전하 분리가 거대한 전위차를 만들고, 이것이 밝은 번개로 방전됩니다.",
      ja: "積乱雲の内部で電荷が分離して巨大な電位差が生まれ、それが明るい稲妻として放電します。",
    },
    cause: {
      en: "Rising and falling ice particles collide within a cumulonimbus cloud, separating positive and negative charges.",
      ko: "적란운 안에서 오르내리는 얼음 입자가 충돌하며 양전하와 음전하를 분리합니다.",
      ja: "積乱雲の中で上下する氷の粒子が衝突し、正と負の電荷を分離させます。",
    },
    mechanism: {
      en: "Negative charge accumulates at the cloud base while positive charge gathers on the ground, until the air's insulation breaks down and a conductive channel forms.",
      ko: "구름 아래에 음전하가, 지면에 양전하가 쌓이다가 공기의 절연이 무너지며 전도성 통로가 형성됩니다.",
      ja: "雲の底に負電荷が、地面に正電荷が溜まり、やがて空気の絶縁が破れて導電性の通り道が形成されます。",
    },
    result: {
      en: "A stepped leader meets an upward streamer, and a massive current surges through the channel as a visible flash and thunder.",
      ko: "계단형 선도방전이 지면의 상향 방전과 만나 거대한 전류가 통로를 지나며 섬광과 천둥을 만듭니다.",
      ja: "階段状のリーダーが地面からの上向き放電と出会い、巨大な電流が通り道を走って閃光と雷鳴を生みます。",
    },
    visualElements: [
      { en: "Cumulonimbus cloud with separated charge layers", ko: "전하층이 분리된 적란운", ja: "電荷層が分離した積乱雲" },
      { en: "Stepped leader branching toward the ground", ko: "지면으로 갈라지며 내려오는 계단형 선도방전", ja: "地面へ枝分かれして下る階段状リーダー" },
      { en: "Upward streamer rising from a tall object", ko: "높은 물체에서 올라오는 상향 방전", ja: "高い物体から立ち上がる上向き放電" },
      { en: "Bright main return stroke channel", ko: "밝은 주 귀환 방전 통로", ja: "明るい主帰還雷撃の通り道" },
    ],
    labelSuggestions: [
      { en: "Negative charge (cloud base)", ko: "음전하 (구름 하부)", ja: "負電荷（雲の底）" },
      { en: "Positive charge (ground)", ko: "양전하 (지면)", ja: "正電荷（地面）" },
      { en: "Stepped leader", ko: "계단형 선도방전", ja: "階段状リーダー" },
      { en: "Return stroke", ko: "귀환 방전", ja: "帰還雷撃" },
    ],
    annotations: [
      { en: "Ice collisions separate charge", ko: "얼음 충돌이 전하를 분리", ja: "氷の衝突が電荷を分離する" },
      { en: "Electric field grows until breakdown", ko: "전기장이 절연 파괴까지 증가", ja: "電場が絶縁破壊まで強まる" },
      { en: "Channel completes, current surges", ko: "통로 완성 후 전류 급증", ja: "通り道が完成し電流が急増する" },
    ],
    styleNotes: {
      en: "Dramatic storm scene with high contrast; emphasize the branching geometry of the discharge.",
      ko: "고대비의 극적인 폭풍 장면; 방전의 가지 구조를 강조합니다.",
      ja: "高コントラストで劇的な嵐の場面。放電の枝分かれ構造を強調します。",
    },
    cautions: {
      en: "Lightning follows a jagged branching path, not a smooth curve; show charge separation clearly.",
      ko: "번개는 매끄러운 곡선이 아니라 들쭉날쭉한 가지 형태입니다. 전하 분리를 명확히 보여주세요.",
      ja: "雷は滑らかな曲線ではなくギザギザに枝分かれします。電荷の分離を明確に示してください。",
    },
    negativeTerms: ["smooth curved beam", "single straight line", "daytime clear sky", "cartoon zigzag"],
    exampleInput: { en: "Explain the formation of lightning", ko: "번개가 어떻게 형성되는지 설명해줘", ja: "雷がどのように発生するか説明して" },
  },
  {
    id: "plate-tectonics",
    slug: "plate-tectonics",
    title: { en: "Plate Tectonics", ko: "판 구조론", ja: "プレートテクトニクス" },
    aliases: ["plate tectonics", "subduction", "tectonic plates", "continental drift", "판 구조론", "섭입", "지각판", "プレートテクトニクス", "沈み込み", "プレート"],
    category: "earth",
    scale: "planetary",
    shortExplanation: {
      en: "Earth's rigid outer plates move over the mantle, and where an oceanic plate sinks beneath another, a subduction zone forms.",
      ko: "지구의 단단한 바깥 판들이 맨틀 위에서 움직이며, 해양판이 다른 판 아래로 가라앉는 곳에서 섭입대가 형성됩니다.",
      ja: "地球の硬い外殻プレートがマントルの上を動き、海洋プレートが別のプレートの下に沈み込む場所で沈み込み帯が形成されます。",
    },
    cause: {
      en: "Convection currents in the mantle drag the lithospheric plates, driving them apart, together, or past each other.",
      ko: "맨틀의 대류가 암석권 판을 끌어당겨 서로 벌어지거나, 부딪히거나, 스쳐 지나가게 합니다.",
      ja: "マントルの対流が岩石圏プレートを引きずり、互いに離れたり、ぶつかったり、すれ違ったりさせます。",
    },
    mechanism: {
      en: "At a convergent boundary, the denser oceanic plate bends and descends into the mantle, melting and generating magma.",
      ko: "수렴 경계에서 밀도가 큰 해양판이 휘어져 맨틀로 내려가며 녹아 마그마를 만듭니다.",
      ja: "収束境界では、密度の高い海洋プレートが曲がってマントルへ沈み込み、融けてマグマを生成します。",
    },
    result: {
      en: "Subduction builds deep ocean trenches, volcanic arcs, and earthquakes along the boundary.",
      ko: "섭입은 깊은 해구, 화산호, 그리고 경계를 따라 지진을 만듭니다.",
      ja: "沈み込みは深い海溝、火山弧、そして境界に沿った地震を生み出します。",
    },
    visualElements: [
      { en: "Cross-section of oceanic and continental plates", ko: "해양판과 대륙판의 단면", ja: "海洋プレートと大陸プレートの断面" },
      { en: "Subducting slab descending into the mantle", ko: "맨틀로 내려가는 섭입 슬랩", ja: "マントルへ沈み込むスラブ" },
      { en: "Mantle convection current arrows", ko: "맨틀 대류 화살표", ja: "マントル対流を示す矢印" },
      { en: "Volcanic arc and ocean trench", ko: "화산호와 해구", ja: "火山弧と海溝" },
    ],
    labelSuggestions: [
      { en: "Oceanic plate", ko: "해양판", ja: "海洋プレート" },
      { en: "Continental plate", ko: "대륙판", ja: "大陸プレート" },
      { en: "Subduction zone", ko: "섭입대", ja: "沈み込み帯" },
      { en: "Mantle convection", ko: "맨틀 대류", ja: "マントル対流" },
    ],
    annotations: [
      { en: "Convection drives plate motion", ko: "대류가 판 운동을 일으킴", ja: "対流がプレートの運動を引き起こす" },
      { en: "Denser plate subducts", ko: "밀도 큰 판이 섭입", ja: "密度の高いプレートが沈み込む" },
      { en: "Melting magma feeds volcanoes", ko: "녹은 마그마가 화산을 형성", ja: "融けたマグマが火山を育てる" },
    ],
    styleNotes: {
      en: "Geological cross-section with layered earth tones; use directional arrows for motion.",
      ko: "층이 드러난 지질 단면과 대지 톤; 운동을 방향 화살표로 표현합니다.",
      ja: "地層が見える地質断面とアースカラー。運動は方向矢印で表現します。",
    },
    cautions: {
      en: "Show the subducting plate at a realistic angle; label the trench and arc separately.",
      ko: "섭입판을 현실적인 각도로 그리고 해구와 화산호를 따로 표기하세요.",
      ja: "沈み込むプレートを現実的な角度で描き、海溝と火山弧を別々に表記してください。",
    },
    negativeTerms: ["flat earth layers", "vertical plate drop", "no mantle", "surface-only view"],
    exampleInput: { en: "Show plate tectonic subduction", ko: "판 구조론의 섭입 과정을 보여줘", ja: "プレートの沈み込みを示して" },
  },
  {
    id: "greenhouse-effect",
    slug: "greenhouse-effect",
    title: { en: "Greenhouse Effect", ko: "온실 효과", ja: "温室効果" },
    aliases: ["greenhouse effect", "global warming mechanism", "atmospheric heat trapping", "온실 효과", "지구 온난화", "温室効果", "地球温暖化"],
    category: "earth",
    scale: "planetary",
    shortExplanation: {
      en: "Greenhouse gases in the atmosphere absorb and re-emit infrared radiation, trapping heat and warming the planet's surface.",
      ko: "대기 중 온실가스가 적외선 복사를 흡수하고 다시 방출하며 열을 가둬 지표를 데웁니다.",
      ja: "大気中の温室効果ガスが赤外線を吸収して再放出し、熱を閉じ込めて地表を暖めます。",
    },
    cause: {
      en: "Sunlight passes through the atmosphere and warms the surface, which re-radiates energy as infrared.",
      ko: "햇빛이 대기를 통과해 지표를 데우고, 지표는 그 에너지를 적외선으로 다시 방출합니다.",
      ja: "太陽光が大気を通り抜けて地表を暖め、地表はそのエネルギーを赤外線として再放射します。",
    },
    mechanism: {
      en: "Gases such as carbon dioxide, methane, and water vapor absorb outgoing infrared and re-emit it in all directions, including back toward the surface.",
      ko: "이산화탄소, 메탄, 수증기 같은 기체가 나가는 적외선을 흡수해 지표 방향을 포함한 모든 방향으로 다시 방출합니다.",
      ja: "二酸化炭素・メタン・水蒸気などの気体が放出される赤外線を吸収し、地表方向を含むあらゆる方向へ再放出します。",
    },
    result: {
      en: "Less heat escapes to space, so the lower atmosphere and surface stay warmer than they otherwise would.",
      ko: "우주로 빠져나가는 열이 줄어 하부 대기와 지표가 더 따뜻하게 유지됩니다.",
      ja: "宇宙へ逃げる熱が減るため、下層大気と地表は本来よりも暖かく保たれます。",
    },
    visualElements: [
      { en: "Incoming shortwave sunlight arrows", ko: "들어오는 단파 햇빛 화살표", ja: "入射する短波の太陽光を示す矢印" },
      { en: "Surface re-emitting infrared radiation", ko: "적외선을 다시 방출하는 지표", ja: "赤外線を再放出する地表" },
      { en: "Greenhouse gas molecules in the atmosphere", ko: "대기 중 온실가스 분자", ja: "大気中の温室効果ガス分子" },
      { en: "Infrared rays reflected back to the surface", ko: "지표로 되돌아오는 적외선", ja: "地表へ戻る赤外線" },
    ],
    labelSuggestions: [
      { en: "Incoming solar radiation", ko: "입사 태양 복사", ja: "入射する太陽放射" },
      { en: "Reflected infrared", ko: "반사된 적외선", ja: "反射された赤外線" },
      { en: "CO₂ / CH₄ / H₂O molecules", ko: "CO₂ / CH₄ / H₂O 분자", ja: "CO₂ / CH₄ / H₂O 分子" },
      { en: "Trapped heat", ko: "갇힌 열", ja: "閉じ込められた熱" },
    ],
    annotations: [
      { en: "Sunlight warms the surface", ko: "햇빛이 지표를 데움", ja: "太陽光が地表を暖める" },
      { en: "Surface emits infrared", ko: "지표가 적외선을 방출", ja: "地表が赤外線を放出する" },
      { en: "Gases re-emit heat downward", ko: "기체가 열을 아래로 재방출", ja: "気体が熱を下方へ再放出する" },
    ],
    styleNotes: {
      en: "Clean atmospheric diagram with distinct arrow colors for shortwave and infrared paths.",
      ko: "단파와 적외선 경로를 다른 색 화살표로 구분한 깔끔한 대기 다이어그램.",
      ja: "短波と赤外線の経路を異なる色の矢印で区別した、すっきりした大気の図。",
    },
    cautions: {
      en: "Distinguish shortwave from infrared; the effect is re-emission, not a solid reflective dome.",
      ko: "단파와 적외선을 구분하세요. 이 효과는 재방출이며 단단한 반사 돔이 아닙니다.",
      ja: "短波と赤外線を区別してください。この効果は再放出であり、硬い反射ドームではありません。",
    },
    negativeTerms: ["solid glass dome", "single arrow direction", "no molecules", "ozone-hole confusion"],
    exampleInput: { en: "Explain the greenhouse effect", ko: "온실 효과를 설명해줘", ja: "温室効果を説明して" },
  },
  {
    id: "photosynthesis",
    slug: "photosynthesis",
    title: { en: "Photosynthesis", ko: "광합성", ja: "光合成" },
    aliases: ["photosynthesis", "plant energy", "chlorophyll process", "광합성", "엽록소", "光合成", "葉緑素"],
    category: "biology",
    scale: "microscopic",
    shortExplanation: {
      en: "Plants convert sunlight, water, and carbon dioxide into glucose and oxygen inside chloroplasts.",
      ko: "식물은 엽록체 안에서 햇빛, 물, 이산화탄소를 포도당과 산소로 바꿉니다.",
      ja: "植物は葉緑体の中で、太陽光・水・二酸化炭素をブドウ糖と酸素に変えます。",
    },
    cause: {
      en: "Chlorophyll in the leaf absorbs light energy, initiating a chain of chemical reactions.",
      ko: "잎 속 엽록소가 빛 에너지를 흡수하며 일련의 화학 반응을 시작합니다.",
      ja: "葉の中の葉緑素が光エネルギーを吸収し、一連の化学反応を開始します。",
    },
    mechanism: {
      en: "Light reactions split water and generate energy carriers; the Calvin cycle then fixes carbon dioxide into sugar.",
      ko: "명반응이 물을 분해하고 에너지 운반체를 만들며, 캘빈 회로가 이산화탄소를 당으로 고정합니다.",
      ja: "明反応が水を分解してエネルギー運搬体を作り、カルビン回路が二酸化炭素を糖へ固定します。",
    },
    result: {
      en: "Glucose stores chemical energy for the plant, and oxygen is released as a byproduct.",
      ko: "포도당은 식물의 화학 에너지를 저장하고, 산소는 부산물로 방출됩니다.",
      ja: "ブドウ糖は植物の化学エネルギーを蓄え、酸素は副産物として放出されます。",
    },
    visualElements: [
      { en: "Leaf cross-section revealing chloroplasts", ko: "엽록체가 드러난 잎 단면", ja: "葉緑体が見える葉の断面" },
      { en: "Sunlight striking chlorophyll", ko: "엽록소에 닿는 햇빛", ja: "葉緑素に当たる太陽光" },
      { en: "Water and CO₂ entering the leaf", ko: "잎으로 들어오는 물과 CO₂", ja: "葉に入る水とCO₂" },
      { en: "Glucose formed and oxygen released", ko: "생성된 포도당과 방출되는 산소", ja: "生成されたブドウ糖と放出される酸素" },
    ],
    labelSuggestions: [
      { en: "Chloroplast", ko: "엽록체", ja: "葉緑体" },
      { en: "Sunlight (light reactions)", ko: "햇빛 (명반응)", ja: "太陽光（明反応）" },
      { en: "CO₂ intake / O₂ release", ko: "CO₂ 흡수 / O₂ 방출", ja: "CO₂ の取り込み / O₂ の放出" },
      { en: "Glucose output", ko: "포도당 생성", ja: "ブドウ糖の生成" },
    ],
    annotations: [
      { en: "Chlorophyll absorbs light", ko: "엽록소가 빛을 흡수", ja: "葉緑素が光を吸収する" },
      { en: "Water is split, energy stored", ko: "물이 분해되고 에너지 저장", ja: "水が分解され、エネルギーが蓄えられる" },
      { en: "CO₂ fixed into glucose", ko: "CO₂가 포도당으로 고정", ja: "CO₂ がブドウ糖に固定される" },
    ],
    styleNotes: {
      en: "Fresh botanical palette with clear cellular detail; show reactant and product flow.",
      ko: "생생한 식물 톤과 명확한 세포 디테일; 반응물과 생성물의 흐름을 보여줍니다.",
      ja: "みずみずしい植物のトーンと明確な細胞ディテール。反応物と生成物の流れを示します。",
    },
    cautions: {
      en: "Keep inputs (light, water, CO₂) and outputs (glucose, O₂) balanced and clearly directional.",
      ko: "입력(빛, 물, CO₂)과 출력(포도당, O₂)을 균형 있게, 방향이 분명하게 표현하세요.",
      ja: "入力（光・水・CO₂）と出力（ブドウ糖・O₂）をバランスよく、方向を明確に表現してください。",
    },
    negativeTerms: ["reversed gas flow", "no chloroplast", "flower-only focus", "night scene"],
    exampleInput: { en: "Show how photosynthesis works", ko: "광합성이 어떻게 일어나는지 보여줘", ja: "光合成がどのように起こるか示して" },
  },
  {
    id: "osmosis",
    slug: "osmosis",
    title: { en: "Osmosis", ko: "삼투", ja: "浸透" },
    aliases: ["osmosis", "cell membrane water", "semipermeable diffusion", "삼투", "삼투압", "浸透", "浸透圧"],
    category: "biology",
    scale: "molecular",
    shortExplanation: {
      en: "Water moves across a semipermeable membrane from a region of lower solute concentration to higher concentration.",
      ko: "물이 반투과성 막을 통해 용질 농도가 낮은 쪽에서 높은 쪽으로 이동합니다.",
      ja: "水が半透膜を通って、溶質濃度の低い側から高い側へ移動します。",
    },
    cause: {
      en: "A concentration difference across the membrane creates a water potential gradient.",
      ko: "막 양쪽의 농도 차이가 물 퍼텐셜 기울기를 만듭니다.",
      ja: "膜の両側の濃度差が水ポテンシャルの勾配を生みます。",
    },
    mechanism: {
      en: "The membrane lets water pass but blocks larger solute particles, so water diffuses to balance the concentrations.",
      ko: "막은 물은 통과시키고 큰 용질 입자는 막아, 농도를 맞추기 위해 물이 확산합니다.",
      ja: "膜は水を通し、大きな溶質粒子を通さないため、濃度をそろえるために水が拡散します。",
    },
    result: {
      en: "Water accumulates on the high-solute side until equilibrium or osmotic pressure balances the flow.",
      ko: "물이 고농도 쪽에 쌓이다가 평형 또는 삼투압이 흐름을 멈출 때까지 이동합니다.",
      ja: "水は高濃度側に溜まり、平衡または浸透圧が流れを釣り合わせるまで移動します。",
    },
    visualElements: [
      { en: "Semipermeable membrane dividing two solutions", ko: "두 용액을 나누는 반투과성 막", ja: "2つの溶液を隔てる半透膜" },
      { en: "Water molecules passing through pores", ko: "구멍을 통과하는 물 분자", ja: "孔を通り抜ける水分子" },
      { en: "Larger solute particles blocked by the membrane", ko: "막에 막힌 큰 용질 입자", ja: "膜に阻まれる大きな溶質粒子" },
      { en: "Rising liquid level on the concentrated side", ko: "고농도 쪽에서 올라가는 액면", ja: "高濃度側で上昇する液面" },
    ],
    labelSuggestions: [
      { en: "Semipermeable membrane", ko: "반투과성 막", ja: "半透膜" },
      { en: "Low solute concentration", ko: "저농도 용질", ja: "低い溶質濃度" },
      { en: "High solute concentration", ko: "고농도 용질", ja: "高い溶質濃度" },
      { en: "Net water movement", ko: "순 물 이동", ja: "正味の水の移動" },
    ],
    annotations: [
      { en: "Concentration gradient drives flow", ko: "농도 기울기가 흐름을 유발", ja: "濃度勾配が流れを引き起こす" },
      { en: "Only water crosses the membrane", ko: "물만 막을 통과", ja: "水だけが膜を通過する" },
      { en: "Levels balance at equilibrium", ko: "평형에서 수위가 균형", ja: "平衡で液面が釣り合う" },
    ],
    styleNotes: {
      en: "Clear molecular illustration with distinct water and solute particles; emphasize directional flow.",
      ko: "물과 용질 입자를 뚜렷이 구분한 분자 일러스트; 방향성 있는 흐름을 강조합니다.",
      ja: "水と溶質の粒子をはっきり区別した分子イラスト。方向性のある流れを強調します。",
    },
    cautions: {
      en: "Water flows toward higher solute concentration; do not reverse the gradient direction.",
      ko: "물은 고농도 쪽으로 흐릅니다. 기울기 방향을 반대로 그리지 마세요.",
      ja: "水は高い溶質濃度の側へ流れます。勾配の向きを逆に描かないでください。",
    },
    negativeTerms: ["solute crossing membrane", "reversed water flow", "no membrane", "equal levels only"],
    exampleInput: { en: "Visualize osmosis across a cell membrane", ko: "세포막을 가로지르는 삼투를 시각화해줘", ja: "細胞膜を横切る浸透を視覚化して" },
  },
  {
    id: "electrolysis",
    slug: "electrolysis",
    title: { en: "Water Electrolysis", ko: "물 전기분해", ja: "水の電気分解" },
    aliases: ["electrolysis", "water electrolysis", "electrolysis of water", "splitting water", "전기분해", "물 전기분해", "電気分解", "水の電気分解"],
    category: "chemistry",
    scale: "molecular",
    shortExplanation: {
      en: "An electric current splits water into hydrogen and oxygen gas at two electrodes.",
      ko: "전류가 물을 두 전극에서 수소와 산소 기체로 분해합니다.",
      ja: "電流が水を2つの電極で水素と酸素の気体に分解します。",
    },
    cause: {
      en: "A voltage applied across electrodes in water drives a non-spontaneous redox reaction.",
      ko: "물속 전극에 전압을 걸면 비자발적 산화·환원 반응이 일어납니다.",
      ja: "水中の電極に電圧をかけると、非自発的な酸化還元反応が進みます。",
    },
    mechanism: {
      en: "At the cathode, water gains electrons to form hydrogen; at the anode, water loses electrons to form oxygen.",
      ko: "음극에서 물이 전자를 얻어 수소가 되고, 양극에서 물이 전자를 잃어 산소가 됩니다.",
      ja: "陰極では水が電子を得て水素になり、陽極では水が電子を失って酸素になります。",
    },
    result: {
      en: "Hydrogen bubbles collect at the cathode and oxygen at the anode, in a 2:1 volume ratio.",
      ko: "수소 기포가 음극에, 산소가 양극에 모이며 부피비는 2:1입니다.",
      ja: "水素の泡が陰極に、酸素が陽極に集まり、体積比は2:1になります。",
    },
    visualElements: [
      { en: "Two electrodes submerged in water", ko: "물에 잠긴 두 전극", ja: "水に浸された2つの電極" },
      { en: "Power source with labeled terminals", ko: "단자가 표시된 전원", ja: "端子が示された電源" },
      { en: "Hydrogen bubbles at the cathode", ko: "음극의 수소 기포", ja: "陰極の水素の泡" },
      { en: "Oxygen bubbles at the anode", ko: "양극의 산소 기포", ja: "陽極の酸素の泡" },
    ],
    labelSuggestions: [
      { en: "Cathode (−) → H₂", ko: "음극 (−) → H₂", ja: "陰極 (−) → H₂" },
      { en: "Anode (+) → O₂", ko: "양극 (+) → O₂", ja: "陽極 (+) → O₂" },
      { en: "Electrolyte solution", ko: "전해질 용액", ja: "電解質溶液" },
      { en: "2:1 hydrogen to oxygen ratio", ko: "수소:산소 = 2:1", ja: "水素:酸素 = 2:1" },
    ],
    annotations: [
      { en: "Current drives the reaction", ko: "전류가 반응을 유발", ja: "電流が反応を進める" },
      { en: "Cathode reduces water to H₂", ko: "음극이 물을 H₂로 환원", ja: "陰極が水を H₂ に還元する" },
      { en: "Anode oxidizes water to O₂", ko: "양극이 물을 O₂로 산화", ja: "陽極が水を O₂ に酸化する" },
    ],
    styleNotes: {
      en: "Clean laboratory diagram; clearly differentiate the two gas streams and electrode polarity.",
      ko: "깔끔한 실험실 다이어그램; 두 기체 흐름과 전극 극성을 명확히 구분합니다.",
      ja: "すっきりした実験室の図。2つの気体の流れと電極の極性を明確に区別します。",
    },
    cautions: {
      en: "Hydrogen forms at the cathode in double the oxygen volume; keep polarity labels correct.",
      ko: "수소는 음극에서 산소의 두 배 부피로 생깁니다. 극성 표기를 정확히 하세요.",
      ja: "水素は陰極で酸素の2倍の体積で発生します。極性の表記を正確に保ってください。",
    },
    negativeTerms: ["swapped gases", "single electrode", "combustion flame", "equal gas volumes"],
    exampleInput: { en: "Show how water electrolysis works", ko: "물 전기분해가 어떻게 일어나는지 보여줘", ja: "水の電気分解がどのように起こるか示して" },
  },
  {
    id: "dna-replication",
    slug: "dna-replication",
    title: { en: "DNA Replication", ko: "DNA 복제", ja: "DNA複製" },
    aliases: ["dna replication", "dna copying", "replication fork", "helicase polymerase", "DNA 복제", "복제 분기점", "DNA複製", "複製フォーク"],
    category: "biology",
    scale: "molecular",
    shortExplanation: {
      en: "The DNA double helix unwinds and each strand serves as a template to build a new complementary strand.",
      ko: "DNA 이중나선이 풀리고 각 가닥이 주형이 되어 새로운 상보 가닥을 만듭니다.",
      ja: "DNAの二重らせんがほどけ、それぞれの鎖が鋳型となって新しい相補鎖を作ります。",
    },
    cause: {
      en: "Before cell division, the cell must produce an identical copy of its genetic information.",
      ko: "세포 분열 전에 세포는 유전 정보의 동일한 사본을 만들어야 합니다.",
      ja: "細胞分裂の前に、細胞は遺伝情報の同一のコピーを作る必要があります。",
    },
    mechanism: {
      en: "Helicase unwinds the helix, and DNA polymerase adds complementary nucleotides to each template strand.",
      ko: "헬리케이스가 나선을 풀고, DNA 중합효소가 각 주형 가닥에 상보 뉴클레오타이드를 붙입니다.",
      ja: "ヘリカーゼがらせんをほどき、DNAポリメラーゼが各鋳型鎖に相補的なヌクレオチドを付加します。",
    },
    result: {
      en: "Two identical DNA molecules form, each containing one original and one new strand.",
      ko: "원본 한 가닥과 새 가닥 하나씩을 가진 동일한 DNA 분자 두 개가 만들어집니다.",
      ja: "元の鎖1本と新しい鎖1本を持つ、同一のDNA分子が2つできあがります。",
    },
    visualElements: [
      { en: "Unwinding double helix at the replication fork", ko: "복제 분기점에서 풀리는 이중나선", ja: "複製フォークでほどける二重らせん" },
      { en: "Helicase separating the strands", ko: "가닥을 분리하는 헬리케이스", ja: "鎖を分離するヘリカーゼ" },
      { en: "Polymerase adding nucleotides", ko: "뉴클레오타이드를 붙이는 중합효소", ja: "ヌクレオチドを付加するポリメラーゼ" },
      { en: "Leading and lagging strands", ko: "선도 가닥과 지연 가닥", ja: "リーディング鎖とラギング鎖" },
    ],
    labelSuggestions: [
      { en: "Replication fork", ko: "복제 분기점", ja: "複製フォーク" },
      { en: "Helicase", ko: "헬리케이스", ja: "ヘリカーゼ" },
      { en: "DNA polymerase", ko: "DNA 중합효소", ja: "DNAポリメラーゼ" },
      { en: "Leading / lagging strand", ko: "선도 / 지연 가닥", ja: "リーディング / ラギング鎖" },
    ],
    annotations: [
      { en: "Helix unwinds into two templates", ko: "나선이 두 주형으로 풀림", ja: "らせんがほどけて2つの鋳型になる" },
      { en: "Bases pair complementarily", ko: "염기가 상보적으로 결합", ja: "塩基が相補的に対合する" },
      { en: "Two identical helices result", ko: "동일한 두 나선이 완성", ja: "同一のらせんが2つできる" },
    ],
    styleNotes: {
      en: "Elegant molecular biology render; use color-coded base pairs and clear enzyme shapes.",
      ko: "우아한 분자생물학 렌더링; 색으로 구분한 염기쌍과 명확한 효소 형태를 사용합니다.",
      ja: "上品な分子生物学のレンダリング。色分けした塩基対と明確な酵素の形状を用います。",
    },
    cautions: {
      en: "Show antiparallel strands and correct base pairing (A–T, G–C); label leading vs lagging.",
      ko: "역평행 가닥과 올바른 염기쌍(A–T, G–C)을 보여주고 선도/지연 가닥을 표기하세요.",
      ja: "逆平行の鎖と正しい塩基対（A–T、G–C）を示し、リーディング鎖とラギング鎖を表記してください。",
    },
    negativeTerms: ["single strand only", "wrong base pairing", "no enzymes", "triple helix"],
    exampleInput: { en: "Show DNA replication at the molecular level", ko: "분자 수준에서 DNA 복제를 보여줘", ja: "分子レベルでDNA複製を示して" },
  },
  {
    id: "mitosis",
    slug: "mitosis",
    title: { en: "Mitosis", ko: "체세포 분열", ja: "体細胞分裂" },
    aliases: ["mitosis", "cell division", "chromosome separation", "체세포 분열", "세포 분열", "体細胞分裂", "細胞分裂"],
    category: "biology",
    scale: "microscopic",
    shortExplanation: {
      en: "A cell divides into two genetically identical daughter cells through an ordered sequence of phases.",
      ko: "한 세포가 정해진 단계를 거쳐 유전적으로 동일한 두 개의 딸세포로 나뉩니다.",
      ja: "1つの細胞が決まった段階を経て、遺伝的に同一な2つの娘細胞に分かれます。",
    },
    cause: {
      en: "Growth, repair, and asexual reproduction require producing new identical cells.",
      ko: "성장, 재생, 무성 생식을 위해 동일한 새 세포를 만들어야 합니다.",
      ja: "成長・修復・無性生殖のために、同一の新しい細胞を作る必要があります。",
    },
    mechanism: {
      en: "Chromosomes condense, align at the center, and are pulled to opposite poles by spindle fibers before the cell splits.",
      ko: "염색체가 응축되어 중앙에 정렬하고, 방추사가 양극으로 끌어당긴 뒤 세포가 나뉩니다.",
      ja: "染色体が凝縮して中央に整列し、紡錘糸が両極へ引っ張った後に細胞が分かれます。",
    },
    result: {
      en: "Two daughter cells form, each with a complete and identical set of chromosomes.",
      ko: "완전하고 동일한 염색체 세트를 가진 두 딸세포가 만들어집니다.",
      ja: "完全で同一の染色体一式を持つ2つの娘細胞ができます。",
    },
    visualElements: [
      { en: "Sequence of prophase to telophase", ko: "전기부터 말기까지의 단계", ja: "前期から終期までの段階" },
      { en: "Condensed chromosomes aligning at the equator", ko: "적도면에 정렬하는 응축 염색체", ja: "赤道面に整列する凝縮した染色体" },
      { en: "Spindle fibers pulling chromatids apart", ko: "염색분체를 끌어당기는 방추사", ja: "染色分体を引き離す紡錘糸" },
      { en: "Cell pinching into two daughter cells", ko: "두 딸세포로 갈라지는 세포", ja: "2つの娘細胞にくびれて分かれる細胞" },
    ],
    labelSuggestions: [
      { en: "Prophase / Metaphase", ko: "전기 / 중기", ja: "前期 / 中期" },
      { en: "Anaphase / Telophase", ko: "후기 / 말기", ja: "後期 / 終期" },
      { en: "Spindle fibers", ko: "방추사", ja: "紡錘糸" },
      { en: "Sister chromatids", ko: "자매 염색분체", ja: "姉妹染色分体" },
    ],
    annotations: [
      { en: "Chromosomes condense and align", ko: "염색체가 응축·정렬", ja: "染色体が凝縮して整列する" },
      { en: "Spindle separates chromatids", ko: "방추사가 염색분체를 분리", ja: "紡錘糸が染色分体を分離する" },
      { en: "Cytoplasm divides in two", ko: "세포질이 둘로 나뉨", ja: "細胞質が2つに分かれる" },
    ],
    styleNotes: {
      en: "Sequential panel layout showing each phase; keep chromosome color consistent across steps.",
      ko: "각 단계를 보여주는 순차 패널 구성; 단계별로 염색체 색을 일관되게 유지합니다.",
      ja: "各段階を示す連続パネル構成。段階を通じて染色体の色を一貫させます。",
    },
    cautions: {
      en: "Mitosis yields two identical diploid cells, not four; distinguish it from meiosis.",
      ko: "체세포 분열은 네 개가 아니라 동일한 두 이배체 세포를 만듭니다. 감수분열과 구분하세요.",
      ja: "体細胞分裂は4つではなく、同一の二倍体細胞を2つ作ります。減数分裂と区別してください。",
    },
    negativeTerms: ["four daughter cells", "crossing over", "haploid result", "random chromosome count"],
    exampleInput: { en: "Explain the phases of mitosis", ko: "체세포 분열의 단계를 설명해줘", ja: "体細胞分裂の段階を説明して" },
  },
  {
    id: "superconductivity",
    slug: "superconductivity",
    title: { en: "Superconductivity", ko: "초전도", ja: "超伝導" },
    aliases: ["superconductivity", "superconductor", "meissner effect", "zero resistance", "초전도", "마이스너 효과", "超伝導", "マイスナー効果"],
    category: "physics",
    scale: "atomic",
    shortExplanation: {
      en: "Below a critical temperature, certain materials conduct electricity with zero resistance and expel magnetic fields.",
      ko: "임계 온도 이하에서 특정 물질은 저항 없이 전기를 흐르게 하고 자기장을 밀어냅니다.",
      ja: "臨界温度以下では、特定の物質が抵抗ゼロで電気を流し、磁場を排除します。",
    },
    cause: {
      en: "Cooling the material below its critical temperature allows electrons to pair up despite their mutual repulsion.",
      ko: "물질을 임계 온도 이하로 냉각하면 서로 밀어내던 전자들이 짝을 이룹니다.",
      ja: "物質を臨界温度以下に冷やすと、互いに反発していた電子が対を作ります。",
    },
    mechanism: {
      en: "Electrons form Cooper pairs mediated by lattice vibrations and move without scattering, eliminating resistance.",
      ko: "전자가 격자 진동을 매개로 쿠퍼 쌍을 이루어 산란 없이 이동하며 저항이 사라집니다.",
      ja: "電子は格子振動を介してクーパー対を形成し、散乱せずに移動して抵抗が消えます。",
    },
    result: {
      en: "Current flows indefinitely, and the Meissner effect makes a magnet levitate above the superconductor.",
      ko: "전류가 무한히 흐르고, 마이스너 효과로 자석이 초전도체 위에 떠오릅니다.",
      ja: "電流が無限に流れ続け、マイスナー効果によって磁石が超伝導体の上に浮きます。",
    },
    visualElements: [
      { en: "Cooled superconductor with cold vapor", ko: "찬 증기가 나오는 냉각된 초전도체", ja: "冷たい蒸気が立つ冷却された超伝導体" },
      { en: "Cooper pairs of electrons moving freely", ko: "자유롭게 움직이는 전자 쿠퍼 쌍", ja: "自由に動く電子のクーパー対" },
      { en: "Magnetic field lines expelled from the material", ko: "물질 밖으로 밀려난 자기력선", ja: "物質の外へ排除された磁力線" },
      { en: "Levitating magnet above the surface", ko: "표면 위에 떠 있는 자석", ja: "表面の上に浮く磁石" },
    ],
    labelSuggestions: [
      { en: "Critical temperature", ko: "임계 온도", ja: "臨界温度" },
      { en: "Cooper pair", ko: "쿠퍼 쌍", ja: "クーパー対" },
      { en: "Zero electrical resistance", ko: "전기 저항 0", ja: "電気抵抗ゼロ" },
      { en: "Meissner effect", ko: "마이스너 효과", ja: "マイスナー効果" },
    ],
    annotations: [
      { en: "Cooling enables electron pairing", ko: "냉각이 전자 짝짓기를 가능하게 함", ja: "冷却が電子の対形成を可能にする" },
      { en: "Cooper pairs flow without scattering", ko: "쿠퍼 쌍이 산란 없이 흐름", ja: "クーパー対が散乱せずに流れる" },
      { en: "Magnetic field is expelled", ko: "자기장이 밀려남", ja: "磁場が排除される" },
    ],
    styleNotes: {
      en: "Cool blue palette with cryogenic mist; emphasize levitation and expelled field lines.",
      ko: "극저온 안개가 있는 차가운 블루 톤; 부상과 밀려난 자기력선을 강조합니다.",
      ja: "極低温の霧を伴う冷たいブルーのトーン。浮上と排除された磁力線を強調します。",
    },
    cautions: {
      en: "The Meissner effect expels field lines rather than blocking them like a shield; show pairing at low temperature.",
      ko: "마이스너 효과는 방패처럼 막는 게 아니라 자기력선을 밀어냅니다. 저온에서의 짝짓기를 보여주세요.",
      ja: "マイスナー効果は盾のように遮るのではなく磁力線を排除します。低温での対形成を示してください。",
    },
    negativeTerms: ["room temperature glow", "magnetic shield wall", "resistive sparks", "single electrons only"],
    exampleInput: { en: "Explain superconductivity", ko: "초전도 현상을 설명해줘", ja: "超伝導現象を説明して" },
  },
  {
    id: "black-hole-accretion",
    slug: "black-hole-accretion",
    title: { en: "Black Hole Accretion Disk", ko: "블랙홀 강착 원반", ja: "ブラックホール降着円盤" },
    aliases: ["black hole", "accretion disk", "black hole accretion", "event horizon", "블랙홀", "강착 원반", "사건의 지평선", "ブラックホール", "降着円盤", "事象の地平面"],
    category: "space",
    scale: "cosmic",
    shortExplanation: {
      en: "Gas spiraling into a black hole forms a superheated disk that glows brightly before crossing the event horizon.",
      ko: "블랙홀로 나선을 그리며 빨려드는 기체가 초고온 원반을 이루어 밝게 빛나다가 사건의 지평선을 넘습니다.",
      ja: "ブラックホールへ渦を巻いて落ちる気体が超高温の円盤を作り、明るく輝いてから事象の地平面を越えます。",
    },
    cause: {
      en: "The black hole's immense gravity pulls in surrounding gas and dust.",
      ko: "블랙홀의 거대한 중력이 주변 기체와 먼지를 끌어당깁니다.",
      ja: "ブラックホールの巨大な重力が周囲の気体と塵を引き寄せます。",
    },
    mechanism: {
      en: "Infalling matter forms a rotating disk where friction and shear heat it to millions of degrees, emitting intense radiation.",
      ko: "떨어지는 물질이 회전 원반을 이루고, 마찰과 전단이 수백만 도까지 가열해 강한 복사를 방출합니다.",
      ja: "落ち込む物質が回転円盤を作り、摩擦とせん断で数百万度まで加熱されて強い放射を放ちます。",
    },
    result: {
      en: "The disk radiates X-rays and light, gravitational lensing warps the view, and relativistic jets may erupt from the poles.",
      ko: "원반이 X선과 빛을 방출하고 중력 렌즈가 시야를 왜곡하며, 양극에서 상대론적 제트가 뿜어질 수 있습니다.",
      ja: "円盤はX線と光を放射し、重力レンズが視界を歪め、両極から相対論的ジェットが噴き出すことがあります。",
    },
    visualElements: [
      { en: "Central black hole with dark event horizon", ko: "어두운 사건의 지평선을 가진 중심 블랙홀", ja: "暗い事象の地平面を持つ中心のブラックホール" },
      { en: "Glowing superheated accretion disk", ko: "빛나는 초고온 강착 원반", ja: "輝く超高温の降着円盤" },
      { en: "Gravitationally lensed light arc", ko: "중력 렌즈로 휘어진 빛의 호", ja: "重力レンズで曲がった光の弧" },
      { en: "Relativistic jets from the poles", ko: "양극에서 나오는 상대론적 제트", ja: "両極から伸びる相対論的ジェット" },
    ],
    labelSuggestions: [
      { en: "Event horizon", ko: "사건의 지평선", ja: "事象の地平面" },
      { en: "Accretion disk", ko: "강착 원반", ja: "降着円盤" },
      { en: "Gravitational lensing", ko: "중력 렌즈 효과", ja: "重力レンズ効果" },
      { en: "Relativistic jet", ko: "상대론적 제트", ja: "相対論的ジェット" },
    ],
    annotations: [
      { en: "Gravity pulls in surrounding matter", ko: "중력이 주변 물질을 끌어당김", ja: "重力が周囲の物質を引き寄せる" },
      { en: "Friction heats the disk", ko: "마찰이 원반을 가열", ja: "摩擦が円盤を加熱する" },
      { en: "Radiation and jets escape", ko: "복사와 제트가 방출됨", ja: "放射とジェットが放出される" },
    ],
    styleNotes: {
      en: "Cinematic cosmic scale with intense orange-to-white disk glow against deep space black.",
      ko: "깊은 우주의 검은 배경에 주황에서 흰색으로 빛나는 원반의 영화적 우주 규모.",
      ja: "深い宇宙の黒を背景に、オレンジから白へ輝く円盤のシネマティックな宇宙スケール。",
    },
    cautions: {
      en: "The event horizon is dark; the visible glow is the disk. Show gravitational lensing, not a solid sphere.",
      ko: "사건의 지평선은 어둡고 빛나는 것은 원반입니다. 단단한 구가 아니라 중력 렌즈를 표현하세요.",
      ja: "事象の地平面は暗く、輝いて見えるのは円盤です。硬い球ではなく重力レンズを表現してください。",
    },
    negativeTerms: ["glowing solid sphere", "whirlpool of water", "no event horizon", "cartoon vortex"],
    exampleInput: { en: "Show how a black hole accretion disk behaves", ko: "블랙홀 강착 원반이 어떻게 작동하는지 보여줘", ja: "ブラックホールの降着円盤の様子を示して" },
  },
  {
    id: "volcanic-eruption",
    slug: "volcanic-eruption",
    title: { en: "Volcanic Eruption", ko: "화산 폭발", ja: "火山の噴火" },
    aliases: ["volcanic eruption", "volcano", "magma eruption", "lava", "화산 폭발", "화산", "마그마", "火山", "噴火", "マグマ"],
    category: "earth",
    scale: "landscape",
    shortExplanation: {
      en: "Molten rock, gas, and ash rise from a magma chamber and burst through the surface of a volcano.",
      ko: "녹은 암석, 가스, 화산재가 마그마 방에서 올라와 화산 표면을 뚫고 분출합니다.",
      ja: "融けた岩石・ガス・火山灰がマグマだまりから上昇し、火山の地表を突き破って噴出します。",
    },
    cause: {
      en: "Pressure builds in a magma chamber as gas-rich molten rock accumulates beneath the crust.",
      ko: "가스가 풍부한 용융 암석이 지각 아래에 쌓이며 마그마 방의 압력이 높아집니다.",
      ja: "ガスに富む融けた岩石が地殻の下に溜まり、マグマだまりの圧力が高まります。",
    },
    mechanism: {
      en: "When pressure exceeds the overlying rock's strength, magma ascends through a conduit and dissolved gases expand rapidly.",
      ko: "압력이 위 암석의 강도를 넘으면 마그마가 화도를 따라 상승하고 용해된 가스가 급격히 팽창합니다.",
      ja: "圧力が上の岩石の強度を超えると、マグマが火道を通って上昇し、溶けていたガスが急激に膨張します。",
    },
    result: {
      en: "Lava flows, ash plumes, and pyroclastic material erupt, reshaping the landscape around the vent.",
      ko: "용암류, 화산재 기둥, 화쇄물이 분출하며 분화구 주변 지형을 바꿉니다.",
      ja: "溶岩流・火山灰の噴煙・火砕物が噴出し、火口周辺の地形を作り変えます。",
    },
    visualElements: [
      { en: "Cross-section of magma chamber and conduit", ko: "마그마 방과 화도의 단면", ja: "マグマだまりと火道の断面" },
      { en: "Rising magma with expanding gas bubbles", ko: "가스 기포가 팽창하는 상승 마그마", ja: "ガスの泡が膨張しながら上昇するマグマ" },
      { en: "Ash plume and volcanic lightning", ko: "화산재 기둥과 화산 번개", ja: "火山灰の噴煙と火山雷" },
      { en: "Lava flows down the slope", ko: "경사면을 흐르는 용암류", ja: "斜面を流れ下る溶岩流" },
    ],
    labelSuggestions: [
      { en: "Magma chamber", ko: "마그마 방", ja: "マグマだまり" },
      { en: "Volcanic conduit", ko: "화도", ja: "火道" },
      { en: "Ash plume", ko: "화산재 기둥", ja: "火山灰の噴煙" },
      { en: "Lava flow", ko: "용암류", ja: "溶岩流" },
    ],
    annotations: [
      { en: "Pressure builds below the surface", ko: "지표 아래에서 압력 상승", ja: "地表の下で圧力が高まる" },
      { en: "Gases expand and drive ascent", ko: "가스 팽창이 상승을 유발", ja: "ガスの膨張が上昇を促す" },
      { en: "Eruption ejects lava and ash", ko: "분출이 용암과 화산재를 방출", ja: "噴火が溶岩と火山灰を放出する" },
    ],
    styleNotes: {
      en: "Dramatic geological cutaway with glowing magma; contrast hot interior against dark rock.",
      ko: "빛나는 마그마가 있는 극적인 지질 단면; 뜨거운 내부와 어두운 암석을 대비합니다.",
      ja: "輝くマグマを含む劇的な地質断面。熱い内部と暗い岩石を対比させます。",
    },
    cautions: {
      en: "Show the internal plumbing, not just surface lava; distinguish ash plume from smoke.",
      ko: "표면 용암뿐 아니라 내부 구조를 보여주고, 화산재 기둥과 연기를 구분하세요.",
      ja: "地表の溶岩だけでなく内部構造を示し、火山灰の噴煙と煙を区別してください。",
    },
    negativeTerms: ["surface-only view", "gray smoke only", "no magma chamber", "gentle fountain"],
    exampleInput: { en: "Visualize a volcanic eruption", ko: "화산 폭발을 시각화해줘", ja: "火山の噴火を視覚化して" },
  },
  {
    id: "electromagnetic-induction",
    slug: "electromagnetic-induction",
    title: { en: "Electromagnetic Induction", ko: "전자기 유도", ja: "電磁誘導" },
    aliases: ["electromagnetic induction", "faraday induction", "induced current", "generator principle", "전자기 유도", "패러데이 법칙", "電磁誘導", "ファラデーの法則"],
    category: "physics",
    scale: "human",
    shortExplanation: {
      en: "A changing magnetic field through a coil induces an electric current in the wire.",
      ko: "코일을 지나는 자기장이 변하면 도선에 전류가 유도됩니다.",
      ja: "コイルを貫く磁場が変化すると、導線に電流が誘導されます。",
    },
    cause: {
      en: "Moving a magnet relative to a coil changes the magnetic flux passing through it.",
      ko: "자석과 코일이 상대적으로 움직이면 코일을 지나는 자기 선속이 변합니다.",
      ja: "磁石とコイルが相対的に動くと、コイルを貫く磁束が変化します。",
    },
    mechanism: {
      en: "By Faraday's law, the changing flux creates an electromotive force that drives electrons around the circuit.",
      ko: "패러데이 법칙에 따라 변하는 선속이 기전력을 만들어 전자를 회로 주위로 흐르게 합니다.",
      ja: "ファラデーの法則により、変化する磁束が起電力を生み、電子を回路に沿って流します。",
    },
    result: {
      en: "An induced current flows in the coil, the basis of generators and transformers.",
      ko: "코일에 유도 전류가 흐르며, 이는 발전기와 변압기의 원리입니다.",
      ja: "コイルに誘導電流が流れます。これは発電機や変圧器の原理です。",
    },
    visualElements: [
      { en: "Bar magnet moving through a wire coil", ko: "도선 코일을 통과하는 막대자석", ja: "導線コイルを通り抜ける棒磁石" },
      { en: "Magnetic field lines linking the coil", ko: "코일과 연결된 자기력선", ja: "コイルと鎖交する磁力線" },
      { en: "Induced current arrows in the wire", ko: "도선의 유도 전류 화살표", ja: "導線内の誘導電流を示す矢印" },
      { en: "Galvanometer deflecting to show current", ko: "전류를 보여주며 편향되는 검류계", ja: "電流を示して振れる検流計" },
    ],
    labelSuggestions: [
      { en: "Moving magnet", ko: "움직이는 자석", ja: "動く磁石" },
      { en: "Changing magnetic flux", ko: "변하는 자기 선속", ja: "変化する磁束" },
      { en: "Induced EMF", ko: "유도 기전력", ja: "誘導起電力" },
      { en: "Induced current", ko: "유도 전류", ja: "誘導電流" },
    ],
    annotations: [
      { en: "Magnet motion changes flux", ko: "자석 운동이 선속을 변화", ja: "磁石の運動が磁束を変える" },
      { en: "Changing flux induces EMF", ko: "변하는 선속이 기전력 유도", ja: "変化する磁束が起電力を誘導する" },
      { en: "Current flows in the coil", ko: "코일에 전류가 흐름", ja: "コイルに電流が流れる" },
    ],
    styleNotes: {
      en: "Clean physics apparatus diagram; use directional arrows for motion, field, and current.",
      ko: "깔끔한 물리 실험 장치 다이어그램; 운동·자기장·전류를 방향 화살표로 표현합니다.",
      ja: "すっきりした物理実験装置の図。運動・磁場・電流を方向矢印で表現します。",
    },
    cautions: {
      en: "Only a changing flux induces current; a stationary magnet produces none. Keep field direction consistent.",
      ko: "변하는 선속만 전류를 유도합니다. 정지한 자석은 전류를 만들지 않습니다. 자기장 방향을 일관되게 유지하세요.",
      ja: "変化する磁束だけが電流を誘導します。静止した磁石は電流を生みません。磁場の向きを一貫させてください。",
    },
    negativeTerms: ["static magnet with current", "no coil", "lightning bolts", "battery source"],
    exampleInput: { en: "Explain electromagnetic induction", ko: "전자기 유도를 설명해줘", ja: "電磁誘導を説明して" },
  },
  {
    id: "combustion",
    slug: "combustion",
    title: { en: "Combustion", ko: "연소", ja: "燃焼" },
    aliases: ["combustion", "burning", "fire reaction", "oxidation flame", "연소", "산화 반응", "燃焼", "酸化反応"],
    category: "chemistry",
    scale: "molecular",
    shortExplanation: {
      en: "A fuel reacts rapidly with oxygen, releasing heat and light and producing new compounds.",
      ko: "연료가 산소와 빠르게 반응해 열과 빛을 방출하고 새로운 화합물을 만듭니다.",
      ja: "燃料が酸素と急速に反応し、熱と光を放って新しい化合物を作ります。",
    },
    cause: {
      en: "Fuel, oxygen, and enough heat to reach the ignition temperature come together — the fire triangle.",
      ko: "연료, 산소, 그리고 발화점에 이를 만큼의 열이 모입니다 — 연소의 삼각형.",
      ja: "燃料・酸素・発火点に達するだけの熱がそろいます——燃焼の三角形です。",
    },
    mechanism: {
      en: "Chemical bonds in the fuel break and reform with oxygen in an exothermic reaction, sustaining a self-feeding flame.",
      ko: "연료의 화학 결합이 끊어지고 산소와 재결합하는 발열 반응이 스스로 유지되는 불꽃을 만듭니다.",
      ja: "燃料の化学結合が切れて酸素と再結合する発熱反応が、自らを維持する炎を作ります。",
    },
    result: {
      en: "The reaction produces carbon dioxide, water vapor, heat, and light as visible flame.",
      ko: "반응은 이산화탄소, 수증기, 열, 그리고 가시적인 불꽃으로서의 빛을 만듭니다.",
      ja: "反応は二酸化炭素・水蒸気・熱、そして目に見える炎としての光を生み出します。",
    },
    visualElements: [
      { en: "Fire triangle of fuel, oxygen, and heat", ko: "연료·산소·열의 연소 삼각형", ja: "燃料・酸素・熱の燃焼の三角形" },
      { en: "Molecular bonds breaking and reforming", ko: "끊어지고 재결합하는 분자 결합", ja: "切れて再結合する分子の結合" },
      { en: "Flame zones from base to tip", ko: "밑에서 끝까지의 불꽃 영역", ja: "根元から先端までの炎の領域" },
      { en: "CO₂ and H₂O products released", ko: "방출되는 CO₂와 H₂O 생성물", ja: "放出される CO₂ と H₂O の生成物" },
    ],
    labelSuggestions: [
      { en: "Fuel + oxygen", ko: "연료 + 산소", ja: "燃料 + 酸素" },
      { en: "Ignition temperature", ko: "발화점", ja: "発火点" },
      { en: "Exothermic reaction", ko: "발열 반응", ja: "発熱反応" },
      { en: "CO₂ + H₂O products", ko: "CO₂ + H₂O 생성물", ja: "CO₂ + H₂O の生成物" },
    ],
    annotations: [
      { en: "Heat brings fuel to ignition", ko: "열이 연료를 발화점에 도달시킴", ja: "熱が燃料を発火点に達させる" },
      { en: "Bonds break and reform with O₂", ko: "결합이 끊기고 O₂와 재결합", ja: "結合が切れて O₂ と再結合する" },
      { en: "Reaction releases heat and light", ko: "반응이 열과 빛을 방출", ja: "反応が熱と光を放出する" },
    ],
    styleNotes: {
      en: "Combine a molecular reaction inset with a macroscopic flame; warm energetic palette.",
      ko: "분자 반응 삽입도와 거시적 불꽃을 결합; 따뜻하고 에너지 넘치는 톤.",
      ja: "分子反応の挿入図と巨視的な炎を組み合わせる。暖かくエネルギッシュなトーン。",
    },
    cautions: {
      en: "Show reactants and products, not just flames; combustion needs oxygen as a reactant.",
      ko: "불꽃만이 아니라 반응물과 생성물을 보여주세요. 연소에는 산소가 반응물로 필요합니다.",
      ja: "炎だけでなく反応物と生成物を示してください。燃焼には反応物として酸素が必要です。",
    },
    negativeTerms: ["flame without fuel", "no oxygen shown", "explosion cloud", "cold blue-only fire"],
    exampleInput: { en: "Explain the chemistry of combustion", ko: "연소의 화학을 설명해줘", ja: "燃焼の化学を説明して" },
  },
  {
    id: "chemical-bond-formation",
    slug: "chemical-bond-formation",
    title: { en: "Chemical Bond Formation", ko: "화학 결합 형성", ja: "化学結合の形成" },
    aliases: ["chemical bond", "chemical bond formation", "covalent bond", "ionic bond", "화학 결합", "공유 결합", "이온 결합", "化学結合", "共有結合", "イオン結合"],
    category: "chemistry",
    scale: "atomic",
    shortExplanation: {
      en: "Atoms join by sharing or transferring electrons to reach a more stable, lower-energy arrangement.",
      ko: "원자들이 전자를 공유하거나 주고받아 더 안정하고 낮은 에너지 상태에 도달하며 결합합니다.",
      ja: "原子どうしが電子を共有または受け渡しして、より安定で低いエネルギーの状態になり結合します。",
    },
    cause: {
      en: "Atoms seek a full outer electron shell, which lowers their overall energy.",
      ko: "원자는 바깥 전자 껍질을 채워 전체 에너지를 낮추려 합니다.",
      ja: "原子は最外殻の電子を満たして全体のエネルギーを下げようとします。",
    },
    mechanism: {
      en: "In covalent bonds atoms share electron pairs; in ionic bonds one atom transfers electrons to another, creating attracting ions.",
      ko: "공유 결합에서는 전자쌍을 공유하고, 이온 결합에서는 한 원자가 전자를 넘겨 서로 끌어당기는 이온을 만듭니다.",
      ja: "共有結合では電子対を共有し、イオン結合では一方の原子が電子を渡して、引き合うイオンを作ります。",
    },
    result: {
      en: "A stable molecule or ionic compound forms, held together by the shared or transferred electrons.",
      ko: "공유되거나 이동한 전자가 붙잡아 안정한 분자나 이온 화합물이 만들어집니다.",
      ja: "共有または移動した電子が結びつけ、安定な分子やイオン化合物ができます。",
    },
    visualElements: [
      { en: "Atoms with labeled electron shells", ko: "전자 껍질이 표시된 원자", ja: "電子殻が示された原子" },
      { en: "Shared electron pair in a covalent bond", ko: "공유 결합의 공유 전자쌍", ja: "共有結合における共有電子対" },
      { en: "Electron transfer forming ions", ko: "이온을 만드는 전자 이동", ja: "イオンを作る電子の移動" },
      { en: "Resulting stable molecule", ko: "완성된 안정한 분자", ja: "完成した安定な分子" },
    ],
    labelSuggestions: [
      { en: "Valence electrons", ko: "원자가 전자", ja: "価電子" },
      { en: "Covalent bond (shared pair)", ko: "공유 결합 (공유쌍)", ja: "共有結合（共有対）" },
      { en: "Ionic bond (transfer)", ko: "이온 결합 (이동)", ja: "イオン結合（移動）" },
      { en: "Stable octet", ko: "안정한 옥텟", ja: "安定なオクテット" },
    ],
    annotations: [
      { en: "Atoms seek full outer shells", ko: "원자가 바깥 껍질을 채우려 함", ja: "原子が最外殻を満たそうとする" },
      { en: "Electrons are shared or transferred", ko: "전자를 공유하거나 이동", ja: "電子が共有または移動する" },
      { en: "A stable compound forms", ko: "안정한 화합물이 형성", ja: "安定な化合物ができる" },
    ],
    styleNotes: {
      en: "Clean atomic-model illustration; differentiate covalent sharing from ionic transfer clearly.",
      ko: "깔끔한 원자 모형 일러스트; 공유 결합의 공유와 이온 결합의 이동을 명확히 구분합니다.",
      ja: "すっきりした原子モデルのイラスト。共有結合の共有とイオン結合の移動を明確に区別します。",
    },
    cautions: {
      en: "Represent electron shells accurately; distinguish covalent from ionic bonding visually.",
      ko: "전자 껍질을 정확히 표현하고 공유 결합과 이온 결합을 시각적으로 구분하세요.",
      ja: "電子殻を正確に表現し、共有結合とイオン結合を視覚的に区別してください。",
    },
    negativeTerms: ["nucleus fusion", "random electron count", "no electron shells", "mixed bond types unlabeled"],
    exampleInput: { en: "Show how a chemical bond forms", ko: "화학 결합이 어떻게 형성되는지 보여줘", ja: "化学結合がどのように形成されるか示して" },
  },
];

export const PHENOMENA_BY_SLUG: Record<string, PhenomenonProfile> =
  Object.fromEntries(PHENOMENA.map((p) => [p.slug, p]));

export function getPhenomenonBySlug(slug: string): PhenomenonProfile | undefined {
  return PHENOMENA_BY_SLUG[slug];
}
